"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Link2, Plus, Sparkles } from "lucide-react";

type Model = { id: string; display_name: string; automation_mode: string; persona_profiles: { display_name: string }[] | { display_name: string } | null; fanvue_connections: { status: string }[] | { status: string } | null };

export default function ModelsPage() {
  const router = useRouter();
  const [models, setModels] = useState<Model[]>([]); const [showForm, setShowForm] = useState(false); const [displayName, setDisplayName] = useState(""); const [personaName, setPersonaName] = useState(""); const [instructions, setInstructions] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function loadModels() { const response = await fetch("/api/models"); const payload = await response.json() as { models?: Model[]; error?: string }; if (response.ok) setModels(payload.models ?? []); else setMessage(payload.error ?? "Models could not be loaded."); }
  useEffect(() => { queueMicrotask(() => { void loadModels(); }); }, []);
  async function createModel(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/models", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName, personaName, instructions }) }); const payload = await response.json() as { error?: string }; if (!response.ok) setMessage(payload.error ?? "Model could not be created."); else { setDisplayName(""); setPersonaName(""); setInstructions(""); setShowForm(false); await loadModels(); } setBusy(false); }
  return <main className="workspace-page"><Link className="workspace-back" href="/"><ArrowLeft size={15} /> Back to inbox</Link><section className="models-page"><div className="models-heading"><div><p className="truth-eyebrow">MODELS &amp; PERSONAS</p><h1>Your model workspace</h1><p>Create independent models and personas before connecting Fanvue.</p></div><button className="truth-primary" onClick={() => setShowForm((value) => !value)}><Plus size={15} /> Add model</button></div>{showForm && <form className="model-form" onSubmit={createModel}><label>Model display name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="e.g. Avery" required /></label><label>Persona name<input value={personaName} onChange={(event) => setPersonaName(event.target.value)} placeholder="e.g. Avery's persona" required /></label><label>Persona instructions<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} placeholder="Tone, boundaries, approved facts, and writing style..." rows={6} /></label><button className="truth-primary" disabled={busy}>{busy ? "Creating..." : "Create model and persona"}</button></form>}{message && <p className="workspace-error" role="alert">{message}</p>}{models.length === 0 && !showForm ? <div className="models-empty"><Sparkles size={23} /><h2>No models yet.</h2><p>Add a model and persona to begin testing Grok safely. Fanvue connection is optional at this stage.</p><button className="truth-primary" onClick={() => setShowForm(true)}><Plus size={15} /> Add your first model</button></div> : <div className="model-list">{models.map((model) => { const persona = Array.isArray(model.persona_profiles) ? model.persona_profiles[0] : model.persona_profiles; const connection = Array.isArray(model.fanvue_connections) ? model.fanvue_connections[0] : model.fanvue_connections; const connected = connection?.status === "healthy"; return <article className="model-card" key={model.id} role="link" tabIndex={0} onClick={() => router.push(`/models/${model.id}`)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); router.push(`/models/${model.id}`); } }}><div><p className="truth-eyebrow">MODEL</p><h2>{model.display_name}</h2><p>{persona?.display_name ?? "No persona"}</p><div className="model-card-actions"><Link className="truth-secondary model-open" href={`/models/${model.id}`} onClick={(event) => event.stopPropagation()}>Open model</Link><Link className="truth-secondary model-connect" href={connected ? `/models/${model.id}?tab=fanvue` : `/api/fanvue/oauth/start?creatorProfileId=${model.id}`} onClick={(event) => event.stopPropagation()}><Link2 size={14} /> {connected ? "Manage Fanvue" : "Connect Fanvue"}</Link></div></div><span className="model-status">{model.automation_mode.toUpperCase()}</span></article>; })}</div>}</section></main>;
}
