"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Activity, Bot, Brain, Cable, Gauge, Save, UserRound } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Tab = "overview" | "persona" | "automation" | "memory" | "fanvue" | "limits" | "diagnostics";
type WorkspaceData = {
  creator: { id: string; displayName: string; fanvueUserUuid: string | null; timezone: string; automationMode: string };
  persona: { id: string; display_name: string; instructions: string; active: boolean } | null;
  connection: { id: string; external_user_uuid: string; status: string; access_token_expires_at: string; last_health_check_at: string | null; updated_at: string } | null;
  automation: { enabled: boolean; approval_required: boolean; quiet_hours_start: string | null; quiet_hours_end: string | null; max_replies_per_hour: number; min_confidence: number; ppv_allowed: boolean; max_ppv_cents: number } | null;
  counts: { conversations: number; memories: number; pendingJobs: number; failedJobs: number };
  latestJob: { status: string; updated_at: string } | null;
  diagnostics: { oldestPendingAt: string | null; lastIncomingAt: string | null; lastGenerationAt: string | null; lastGrokLatencyMs: number | null; lastSendAt: string | null };
  failedJobs: Array<{ id: string; conversation_id: string; processing_stage: string; last_error: string | null; attempts: number; created_at: string }>;
  traces: Array<{ id: number; automation_job_id: string | null; event: string; duration_ms: number | null; created_at: string }>;
};
const tabs: Tab[] = ["overview", "persona", "automation", "memory", "fanvue", "limits", "diagnostics"];
const modeLabel = (mode: string) => mode === "off" ? "Off" : mode === "draft" ? "Draft only" : mode === "auto_safe" ? "Auto" : "Full auto";

export default function ModelWorkspace({ initial }: { initial: WorkspaceData }) {
  const router = useRouter(); const searchParams = useSearchParams();
  const requestedTab = searchParams.get("tab") as Tab | null;
  const [tab, setTab] = useState<Tab>(requestedTab && tabs.includes(requestedTab) ? requestedTab : "overview");
  const [persona, setPersona] = useState(initial.persona ?? { id: "", display_name: initial.creator.displayName, instructions: "", active: false });
  const [automation, setAutomation] = useState({ enabled: initial.automation?.enabled ?? initial.creator.automationMode !== "off", approvalRequired: initial.automation?.approval_required ?? true, quietHoursStart: initial.automation?.quiet_hours_start ?? "", quietHoursEnd: initial.automation?.quiet_hours_end ?? "", maxRepliesPerHour: initial.automation?.max_replies_per_hour ?? 20, minConfidence: Number(initial.automation?.min_confidence ?? 0.75), ppvAllowed: initial.automation?.ppv_allowed ?? false, maxPpvCents: initial.automation?.max_ppv_cents ?? 50000, automationMode: initial.creator.automationMode });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [realtime, setRealtime] = useState<"Reconnecting" | "Live" | "Offline">("Reconnecting");
  const connected = initial.connection?.status === "healthy";
  const worker = initial.counts.pendingJobs > 0 ? (realtime === "Offline" ? "Offline" : "Delayed") : "Healthy";
  useEffect(() => { const supabase = createSupabaseBrowserClient(); const channel = supabase.channel(`model-diagnostics:${initial.creator.id}`).on("postgres_changes", { event: "*", schema: "public", table: "automation_jobs", filter: `creator_profile_id=eq.${initial.creator.id}` }, () => router.refresh()).subscribe((status) => setRealtime(status === "SUBSCRIBED" ? "Live" : status === "CHANNEL_ERROR" || status === "TIMED_OUT" ? "Offline" : "Reconnecting")); return () => { void supabase.removeChannel(channel); }; }, [initial.creator.id, router]);
  function chooseTab(next: Tab) { setTab(next); router.replace(`/models/${initial.creator.id}?tab=${next}`, { scroll: false }); }
  async function save(event: FormEvent, section: "persona" | "automation") { event.preventDefault(); setSaving(true); setMessage(""); const body = section === "persona" ? { section, displayName: persona.display_name, instructions: persona.instructions, active: persona.active } : { section, ...automation }; const response = await fetch(`/api/models/${initial.creator.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; setMessage(response.ok ? "Saved." : payload.error ?? "Changes could not be saved."); setSaving(false); if (response.ok) router.refresh(); }

  return <section className="model-workspace"><header className="model-workspace-header"><div><p className="truth-eyebrow">MODEL WORKSPACE</p><h1>{initial.creator.displayName}</h1><div className="workspace-badges"><span>Fanvue: {connected ? "Connected" : "Not connected"}</span><span>AI: {modeLabel(initial.creator.automationMode)}</span><span>Persona: {initial.persona?.active ? "Active" : "Missing"}</span></div></div></header><nav className="model-tabs" aria-label="Model workspace sections">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => chooseTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>{message && <p className="workspace-save-message" role="status">{message}</p>}
  {tab === "overview" && <div className="workspace-panel"><h2>Overview</h2><div className="workspace-stat-grid"><Stat icon={<UserRound size={18} />} label="Model" value={initial.creator.displayName} detail={initial.creator.timezone} /><Stat icon={<Cable size={18} />} label="Fanvue account" value={connected ? "Connected" : "Not connected"} detail={initial.connection?.external_user_uuid ?? initial.creator.fanvueUserUuid ?? "No account"} /><Stat icon={<Bot size={18} />} label="Automation" value={modeLabel(initial.creator.automationMode)} detail={automation.enabled ? "Enabled" : "Disabled"} /><Stat icon={<Brain size={18} />} label="Persona" value={initial.persona?.active ? "Active" : "Missing"} detail={initial.persona?.display_name ?? "Create a persona"} /><Stat icon={<Activity size={18} />} label="Recent conversations" value={String(initial.counts.conversations)} detail="For this model only" /><Stat icon={<Gauge size={18} />} label="AI worker" value={worker} detail={`${initial.counts.pendingJobs} pending`} /></div></div>}
  {tab === "persona" && <form className="workspace-panel workspace-form" onSubmit={(event) => save(event, "persona")}><h2>Persona</h2><label>Display name<input value={persona.display_name} onChange={(event) => setPersona({ ...persona, display_name: event.target.value })} required /></label><label>Instructions<textarea rows={12} value={persona.instructions} onChange={(event) => setPersona({ ...persona, instructions: event.target.value })} /></label><label className="workspace-check"><input type="checkbox" checked={persona.active} onChange={(event) => setPersona({ ...persona, active: event.target.checked })} /> Active persona</label><button className="truth-primary" disabled={saving}><Save size={14} /> {saving ? "Saving..." : "Save persona"}</button></form>}
  {tab === "automation" && <form className="workspace-panel workspace-form" onSubmit={(event) => save(event, "automation")}><h2>Automation</h2><label>Mode<select value={automation.automationMode} onChange={(event) => setAutomation({ ...automation, automationMode: event.target.value })}><option value="off">Off</option><option value="draft">Draft only</option><option value="auto_safe">Auto</option><option value="full_auto">Full auto</option></select></label><label className="workspace-check"><input type="checkbox" checked={automation.enabled} onChange={(event) => setAutomation({ ...automation, enabled: event.target.checked })} /> Automation enabled</label><label className="workspace-check"><input type="checkbox" checked={automation.approvalRequired} onChange={(event) => setAutomation({ ...automation, approvalRequired: event.target.checked })} /> Approval required</label><div className="workspace-form-row"><label>Quiet hours start<input type="time" value={automation.quietHoursStart} onChange={(event) => setAutomation({ ...automation, quietHoursStart: event.target.value })} /></label><label>Quiet hours end<input type="time" value={automation.quietHoursEnd} onChange={(event) => setAutomation({ ...automation, quietHoursEnd: event.target.value })} /></label></div><label>Max replies/hour<input type="number" min="1" max="500" value={automation.maxRepliesPerHour} onChange={(event) => setAutomation({ ...automation, maxRepliesPerHour: Number(event.target.value) })} /></label><label>Minimum confidence<input type="number" min="0" max="1" step="0.05" value={automation.minConfidence} onChange={(event) => setAutomation({ ...automation, minConfidence: Number(event.target.value) })} /></label><button className="truth-primary" disabled={saving}><Save size={14} /> {saving ? "Saving..." : "Save automation"}</button></form>}
  {tab === "memory" && <div className="workspace-panel"><h2>Memory</h2><div className="workspace-detail-list"><p><strong>Active memory records</strong><span>{initial.counts.memories}</span></p><p><strong>Scope</strong><span>{initial.creator.displayName} fans only</span></p><p><strong>Isolation</strong><span>Filtered by creator profile ID</span></p></div></div>}
  {tab === "fanvue" && <div className="workspace-panel"><h2>Fanvue</h2><div className="workspace-detail-list"><p><strong>Connection status</strong><span>{initial.connection?.status ?? "Not connected"}</span></p><p><strong>Connected account</strong><span>{initial.connection?.external_user_uuid ?? "—"}</span></p><p><strong>Token health</strong><span>{initial.connection ? (new Date(initial.connection.access_token_expires_at) > new Date() ? "Valid" : "Refresh required") : "—"}</span></p><p><strong>Last health check</strong><span>{initial.connection?.last_health_check_at ? new Date(initial.connection.last_health_check_at).toLocaleString() : "Not checked"}</span></p></div><Link className="truth-primary workspace-inline-action" href={`/api/fanvue/oauth/start?creatorProfileId=${initial.creator.id}`}>{connected ? "Reconnect Fanvue" : "Connect Fanvue"}</Link></div>}
  {tab === "limits" && <div className="workspace-panel"><h2>Limits</h2><div className="workspace-detail-list"><p><strong>Max replies/hour</strong><span>{automation.maxRepliesPerHour}</span></p><p><strong>Minimum confidence</strong><span>{Math.round(automation.minConfidence * 100)}%</span></p><p><strong>PPV allowed</strong><span>{automation.ppvAllowed ? "Yes" : "No"}</span></p><p><strong>Maximum PPV</strong><span>${(automation.maxPpvCents / 100).toFixed(2)}</span></p></div></div>}
  {tab === "diagnostics" && <div className="workspace-panel"><h2>Diagnostics</h2><div className="workspace-detail-list"><p><strong>Fanvue</strong><span>{connected ? "Connected" : initial.connection?.status ?? "Not connected"}</span></p><p><strong>Automation</strong><span>{modeLabel(initial.creator.automationMode)}</span></p><p><strong>Persona</strong><span>{initial.persona?.active ? "Active" : "Missing"}</span></p><p><strong>Worker</strong><span>{worker}</span></p><p><strong>Grok</strong><span>{initial.diagnostics.lastGenerationAt ? `Healthy · ${initial.diagnostics.lastGrokLatencyMs ?? "?"}ms` : "No verified generation"}</span></p><p><strong>Realtime</strong><span>{realtime}</span></p><p><strong>Queue</strong><span>{initial.counts.pendingJobs} pending</span></p><p><strong>Oldest pending</strong><span>{initial.diagnostics.oldestPendingAt ? `Since ${new Date(initial.diagnostics.oldestPendingAt).toLocaleString()}` : "—"}</span></p><p><strong>Failed</strong><span>{initial.counts.failedJobs}</span></p><p><strong>Last incoming</strong><span>{initial.diagnostics.lastIncomingAt ? new Date(initial.diagnostics.lastIncomingAt).toLocaleString() : "—"}</span></p><p><strong>Last AI generation</strong><span>{initial.diagnostics.lastGenerationAt ? new Date(initial.diagnostics.lastGenerationAt).toLocaleString() : "—"}</span></p><p><strong>Last Fanvue send</strong><span>{initial.diagnostics.lastSendAt ? new Date(initial.diagnostics.lastSendAt).toLocaleString() : "—"}</span></p></div>{initial.failedJobs.length > 0 && <><h3>Failed jobs</h3><div className="workspace-detail-list">{initial.failedJobs.map((job) => <p key={job.id}><strong>{new Date(job.created_at).toLocaleString()} · {job.processing_stage}</strong><span>{job.last_error ?? "Unknown error"} · {job.attempts} attempts · <Link href={`/?conversation=${job.conversation_id}`}>Open conversation</Link></span></p>)}</div></>}{initial.traces.length > 0 && <><h3>Recent trace</h3><div className="workspace-detail-list">{initial.traces.map((entry) => <p key={entry.id}><strong>{entry.event}</strong><span>{entry.duration_ms !== null ? `${entry.duration_ms}ms · ` : ""}{new Date(entry.created_at).toLocaleString()}</span></p>)}</div></>}</div>}</section>;
}

function Stat({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="workspace-stat"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>; }
